"""Turn the hopeturtles.org ASCII turtle into stroke paths for the app's
adaptive-icon foreground (108x108 viewport, art inside the 66dp safe circle).

    python3 tools/ascii_icon.py <turtles-ascii-logo.txt> app/src/main/res preview.png

Writes res/drawable/ic_launcher_foreground.xml and a PNG preview (needs
Pillow) with the safe circle drawn in pink.
"""
import sys
from PIL import Image, ImageDraw

ART = open(sys.argv[1]).read().rstrip("\n").split("\n")
W, H = 3.3, 6.6          # character cell
SW = 2.2                  # stroke width

IN = 0.2                  # glyph inset, keeps the ASCII look
segs, eyes = [], []
for r, line in enumerate(ART):
    for c, ch in enumerate(line):
        x0, y0, x1, y1 = c * W, r * H, (c + 1) * W, (r + 1) * H
        if ch == "_":
            # one segment per run of underscores, inset like a glyph
            if c and line[c - 1] == "_": continue
            n = len(line[c:]) - len(line[c:].lstrip("_"))
            segs.append((x0 + IN * W, y1, c * W + n * W - IN * W, y1))
        elif ch == "-": segs.append((x0, (y0 + y1) / 2, x1, (y0 + y1) / 2))
        elif ch == "|": segs.append(((x0 + x1) / 2, y0 + IN * H, (x0 + x1) / 2, y1 - IN * H))
        elif ch == "/": segs.append((x0 + IN * W, y1 - IN * H, x1 - IN * W, y0 + IN * H))
        elif ch == "\\": segs.append((x0 + IN * W, y0 + IN * H, x1 - IN * W, y1 - IN * H))
        elif ch in "0O": eyes.append(((x0 + x1) / 2, (y0 + y1) / 2))

xs = [p for s in segs for p in (s[0], s[2])] + [e[0] for e in eyes]
ys = [p for s in segs for p in (s[1], s[3])] + [e[1] for e in eyes]
dx = 54 - (min(xs) + max(xs)) / 2
dy = 54 - (min(ys) + max(ys)) / 2
segs = [(a + dx, b + dy, c + dx, d + dy) for a, b, c, d in segs]
eyes = [(a + dx, b + dy) for a, b in eyes]
print(f"bbox w={max(xs)-min(xs):.1f} h={max(ys)-min(ys):.1f}", file=sys.stderr)

f = lambda v: f"{v:.2f}".rstrip("0").rstrip(".")
path = "".join(f"M{f(a)},{f(b)}L{f(c)},{f(d)}" for a, b, c, d in segs)
RX, RY = 1.25, 2.0
eye = "".join(f"M{f(x-RX)},{f(y)}a{f(RX)},{f(RY)} 0 1,0 {f(2*RX)},0a{f(RX)},{f(RY)} 0 1,0 {f(-2*RX)},0Z" for x, y in eyes)

def vector(color):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- The smiling ASCII turtle (hopeturtles.org turtles-ascii-logo.txt) as
     strokes. 108dp adaptive-icon canvas; the art fits the 66dp safe zone.
     Generated by tools/ascii_icon.py; regenerate rather than hand-edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:pathData="{path}"
        android:strokeColor="{color}"
        android:strokeWidth="{SW}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />
    <path
        android:pathData="{eye}"
        android:fillColor="{color}" />
</vector>
'''
out = sys.argv[2]
open(f"{out}/drawable/ic_launcher_foreground.xml", "w").write(vector("#FFFFFFFF"))

# preview at 8x, with the 66dp safe circle and a circular mask hint
S = 8
im = Image.new("RGB", (108 * S, 108 * S), "#017919")
d = ImageDraw.Draw(im)
for a, b, c, e in segs:
    d.line([(a * S, b * S), (c * S, e * S)], fill="white", width=int(SW * S))
    for x, y in ((a, b), (c, e)):
        d.ellipse([(x - SW / 2) * S, (y - SW / 2) * S, (x + SW / 2) * S, (y + SW / 2) * S], fill="white")
for x, y in eyes:
    d.ellipse([(x - RX) * S, (y - RY) * S, (x + RX) * S, (y + RY) * S], fill="white")
d.ellipse([21 * S, 21 * S, 87 * S, 87 * S], outline="#ec8fc0", width=2)
im.save(sys.argv[3])
